all:
  children:
    servers:
      hosts:
        borgsrv:
          ansible_host: 192.168.200.10
    clients:
      hosts:
        c01:
          ansible_host: 192.168.200.20
        c02:
          ansible_host: 192.168.200.21
  vars:
    ansible_user: ops
    ansible_private_key_file: /home/frank/test/ansible/sshid
    ansible_python_interpreter: /usr/bin/python3

