all:
  children:
    servers:
      hosts:
        borgsrv:
          ansible_host: 192.168.200.10
          backup_operator_account: borgadm
          config_directory: "/home/borgadm/backup-config"
          backup_directory: "/mnt/backup"

    clients:
      hosts:

        c01:
          ansible_host: 192.168.200.20
          volumes:
            - name: c01-etc
              paths: "/etc"
            - name: c01-var
              paths: "/var"

        c02:
          ansible_host: 192.168.200.21
          volumes:
            - name: c02
              paths: "/etc /home"
          deploy_borg: false

  vars:
    ansible_user: ops
    ansible_private_key_file: /home/frank/test/ansible/sshid
    ansible_python_interpreter: /usr/bin/python3

