# server-setup.yml
---
- name: initial setup on server
  hosts: servers
  become: yes
  tags: server

  roles:
    - borgbackup-exec

  tasks:
    - name: install packages
      package:
        name:
          - openssl
          - rsync
        state: present

    - name: ensure borg group exists
      group:
        name: borg
        state: present

    - name: set up directory for storing backups
      file:
        path: "{{ backup_directory }}"
        state: directory
        owner: root
        group: borg
        mode: '1770'

    - name: set up config directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ config_directory }}"
        - "{{ config_directory }}/etc"

    - name: copy bin directory to server
      synchronize:
        src: bin
        dest: "{{ config_directory }}/"
        archive: no
        recursive: yes
        links: yes
        perms: yes

    - name: create ssh keypair for logging into the backup clients
      openssh_keypair:
        path: "{{ config_directory }}/sshid_borg"
        type: rsa
        state: present
        force: no
    
    - name: set up server config file
      template:
        src: "templates/backup.conf.j2"
        dest: "{{ config_directory}}/etc/backup.conf"

