---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    instances:
      - name: borgsrv
        ip: "192.168.200.10"
      - name: c01
        ip: "192.168.200.20"
      - name: c02
        ip: "192.168.200.21"

  tasks:
    - name: create lxd containers
      lxd_container:
        name: "{{ item.name }}"
        source:
          type: image
          mode: pull
          server: "https://images.linuxcontainers.org"
          protocol: simplestreams
          alias: "debian/10/cloud"
        profiles:
          - cloud
        devices:
          eth0:
            ipv4.address: "{{ item.ip }}"
            name: eth0
            network: lxdbr0
            type: nic
        state: started
        wait_for_ipv4_addresses: true
        timeout: 60
      with_items: "{{ instances }}"

