# server-setup.yml
---
- name: initial setup on server
  hosts: servers
  become: yes

  roles:
    - borgbackup-exec

  tasks:
    - name: install packages
      package:
        name:
          - openssl
          - rsync
        state: present

    - name: ensure borg group exists
      group:
        name: borg
        state: present

    - name: ensure operator account exists
      user:
        name: "{{ backup_operator_account }}"
        comment: Borg Operator Account
        create_home: yes
        shell: /bin/bash

    - name: set up directory for storing backups
      file:
        path: "{{ backup_directory }}"
        state: directory
        owner: root
        group: borg
        mode: '1770'

    - name: set up config directories
      file:
        path: "{{ item }}"
        owner: "{{ backup_operator_account }}"
        group: "{{ backup_operator_account }}"
        state: directory
      loop:
        - "{{ config_directory }}"
        - "{{ config_directory }}/etc"

    - name: copy bin directory to server
      synchronize:
        src: "../bin"
        dest: "{{ config_directory }}/"
        archive: yes
        rsync_opts:
          - "--chown={{ backup_operator_account }}:{{ backup_operator_account }}"

    - name: create ssh keypair for logging into the backup clients
      openssh_keypair:
        path: "{{ config_directory }}/sshid_borg"
        owner: "{{ backup_operator_account }}"
        group: "{{ backup_operator_account }}"
        type: rsa
        state: present
        force: no
    
    - name: set up server config file
      template:
        src: "templates/backup.conf.j2"
        dest: "{{ config_directory}}/etc/backup.conf"
        owner: "{{ backup_operator_account }}"
        group: "{{ backup_operator_account }}"

    - name: set up group config file
      copy:
        src: "templates/ALL.conf"
        dest: "{{ config_directory}}/etc/ALL.conf"
        owner: "{{ backup_operator_account }}"
        group: "{{ backup_operator_account }}"
        force: no
